# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwLogExtractor < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/cw-log-extractor/releases/download/v0.0.1/cw-log-extractor_Darwin_x86_64.tar.gz"
      sha256 "88aff0184933ee1f8fd5acb6201c9f5fa095f8ac044aad6eb0c09af60d5af2ef"

      def install
        bin.install "cw-log-extractor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/cw-log-extractor/releases/download/v0.0.1/cw-log-extractor_Darwin_arm64.tar.gz"
      sha256 "63d664432170f8011243154d1dc9cafdb586940366a22c3cffd00bad6d817760"

      def install
        bin.install "cw-log-extractor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/cw-log-extractor/releases/download/v0.0.1/cw-log-extractor_Linux_x86_64.tar.gz"
      sha256 "de5ee9849e29d4abbd6696165a85b36dbb6b755986b5bdadfb53c98e50116ed5"
      def install
        bin.install "cw-log-extractor"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/cw-log-extractor/releases/download/v0.0.1/cw-log-extractor_Linux_arm64.tar.gz"
      sha256 "2cfd587ce1686dea14b8f437c41f915099141be15ead0cd478f2c4d80d08f602"
      def install
        bin.install "cw-log-extractor"
      end
    end
  end
end
