# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CwLogExtractor < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/cw-log-extractor/releases/download/v0.0.1/cw-log-extractor_Darwin_x86_64.tar.gz"
      sha256 "d88f88b88a1872c1e846dbd6ce61d013a73e437a3dc6f516f510e6569dba3dfd"

      def install
        bin.install "cw-log-extractor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/cw-log-extractor/releases/download/v0.0.1/cw-log-extractor_Darwin_arm64.tar.gz"
      sha256 "6f6248d580ae4f47716b72bec2935722e9fabd8bf934430f5757481135c62b3c"

      def install
        bin.install "cw-log-extractor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/cw-log-extractor/releases/download/v0.0.1/cw-log-extractor_Linux_x86_64.tar.gz"
      sha256 "0a3a7b5f140a1890a8aa7e035599772349f4355201e539871b15209a98786ffc"
      def install
        bin.install "cw-log-extractor"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/cw-log-extractor/releases/download/v0.0.1/cw-log-extractor_Linux_arm64.tar.gz"
      sha256 "96f5416e5ba123a1760b674b863681ef237b24800ae04d08cd6b22b50d9aeaba"
      def install
        bin.install "cw-log-extractor"
      end
    end
  end
end
