# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleGoreleaserSystemd < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.2/example-goreleaser-systemd_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "05afe1ee80b68f8937ca0894cd4be38319fcbdcc1066ef15764560c62ff22ec9"

      def install
        bin.install "example-goreleaser-systemd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.2/example-goreleaser-systemd_0.0.2_Darwin_arm64.tar.gz"
      sha256 "61989140343bee530fdb3ae3c79d9c88322465bcf8b47158f936b3bcdef74986"

      def install
        bin.install "example-goreleaser-systemd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.2/example-goreleaser-systemd_0.0.2_Linux_arm64.tar.gz"
      sha256 "7fbbc7c8bd55a42454aaa1de66bbd19f64d66bcfb001b1f0d4b7cf7c600252ff"

      def install
        bin.install "example-goreleaser-systemd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.2/example-goreleaser-systemd_0.0.2_Linux_x86_64.tar.gz"
      sha256 "02e2a5a1c197856ad8edf352c6cf9fc2758172b394ea746283c1b8ad3e6a4157"

      def install
        bin.install "example-goreleaser-systemd"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.2/example-goreleaser-systemd_0.0.2_Linux_armv6.tar.gz"
      sha256 "5b082e61a3cc9236e8e7a031bda4a8d7327298f235214b83c06b24bda9c89030"

      def install
        bin.install "example-goreleaser-systemd"
      end
    end
  end

  service do
    run: opt_bin/"example-goreleaser-systemd"
  end
end
