# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleGoreleaserService < Formula
  desc ""
  homepage ""
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.9/example-goreleaser-service_0.0.9_Darwin_x86_64.tar.gz"
      sha256 "3a0985ce47ce0334b86bafd91c3480f79742b34ede6b9991b2a41010bfaa1bfa"

      def install
        bin.install "example-goreleaser-service"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.9/example-goreleaser-service_0.0.9_Darwin_arm64.tar.gz"
      sha256 "b821a59150d0f7fd0abd601add25815d128ceaf72d63a91617d1671e991883b2"

      def install
        bin.install "example-goreleaser-service"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.9/example-goreleaser-service_0.0.9_Linux_armv6.tar.gz"
      sha256 "484e421d6c0dfeffae33b87b041023e9ee650c567f248d5a2d06f8743b42afff"

      def install
        bin.install "example-goreleaser-service"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.9/example-goreleaser-service_0.0.9_Linux_x86_64.tar.gz"
      sha256 "ef5ee84fa76db424d4fd3a0b9b6c2e102166858a0d50d1b4666f12795de0cbfe"

      def install
        bin.install "example-goreleaser-service"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.9/example-goreleaser-service_0.0.9_Linux_arm64.tar.gz"
      sha256 "eb39e77c1329d2758ff26af1c92e5061f4b2e5c521c30e1fdbe4aa1ec6c0e30c"

      def install
        bin.install "example-goreleaser-service"
      end
    end
  end

  def post_install
    (var/"lib/example-goreleaser-service").mkpath
  end

  service do
    run opt_bin/"example-goreleaser-service"
    log_path var/"log/example-goreleaser-service-stdout.log"
    error_log_path var/"log/example-goreleaser-service-stderr.log"
    working_dir var/"lib/example-goreleaser-service"
  end
end
