# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleGoreleaserService < Formula
  desc ""
  homepage ""
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.6/example-goreleaser-service_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "88cba12174f0d20b5e84e58cd35b7ff1113255ae65a7639aee7523442145d4d5"

      def install
        bin.install "example-goreleaser-service"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.6/example-goreleaser-service_0.0.6_Darwin_arm64.tar.gz"
      sha256 "8f594325c6de823f1ecc1e5879e5b887fa90234163adbac79ad3559ea6c4c20d"

      def install
        bin.install "example-goreleaser-service"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.6/example-goreleaser-service_0.0.6_Linux_armv6.tar.gz"
      sha256 "db645f530afad2b96156a9745c9ba001a2f5b0ef58e9f9377b3f6bfa526ff2dc"

      def install
        bin.install "example-goreleaser-service"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.6/example-goreleaser-service_0.0.6_Linux_x86_64.tar.gz"
      sha256 "b1e2221792ab9632fffcfc086f34cb3781c5cb6301eeed24b975f25703e0a14b"

      def install
        bin.install "example-goreleaser-service"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.6/example-goreleaser-service_0.0.6_Linux_arm64.tar.gz"
      sha256 "d2990eb00fb4995ec326abec18f810d8686ee555c30e1c7b15d93448f9546c0f"

      def install
        bin.install "example-goreleaser-service"
      end
    end
  end

  def post_install
    (var/"lib/example-goreleaser-service").mkpath
  end

  service do
    run opt_bin/"example-goreleaser-service"
    log_path var/"log/example-goreleaser-service-stdout.log"
    error_log_path var/"log/example-goreleaser-service-stderr.log"
    working_dir var/"lib/example-goreleaser-service"
  end
end
