# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleGoreleaserSystemdService < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.1/example-goreleaser-systemd-service_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "010f29bf5d8cb2efd988a2ef0546abf48bf5651a687c76fb57539741b328c47c"

      def install
        bin.install "example-goreleaser-systemd-service"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.1/example-goreleaser-systemd-service_0.0.1_Darwin_arm64.tar.gz"
      sha256 "980ffa3191a81ea39753adb58ea0522c2b8fca06c73ef656e8e8158241409734"

      def install
        bin.install "example-goreleaser-systemd-service"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.1/example-goreleaser-systemd-service_0.0.1_Linux_armv6.tar.gz"
      sha256 "909b99e1f20b05346c0cd7bf47710d07315fb45448cc26db0354d34c55272a3b"

      def install
        bin.install "example-goreleaser-systemd-service"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.1/example-goreleaser-systemd-service_0.0.1_Linux_arm64.tar.gz"
      sha256 "e158f558921b0c643cfaa3e579428f45a0688c82d150774c9328e0423dd84c1d"

      def install
        bin.install "example-goreleaser-systemd-service"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/example-goreleaser-systemd-service/releases/download/v0.0.1/example-goreleaser-systemd-service_0.0.1_Linux_x86_64.tar.gz"
      sha256 "6efa009e63665af7e839d553361a316fc1570847acd9cdc2b2340c5509870190"

      def install
        bin.install "example-goreleaser-systemd-service"
      end
    end
  end
end
