# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exoskeleton < Formula
  desc ""
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/exoskeleton/releases/download/v0.1.1/exoskeleton_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "a34de7b44c1220f0053fa99f1042780c3a169dfe58f70823a167e0a986a2fc97"

      def install
        bin.install "exoskeleton"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/exoskeleton/releases/download/v0.1.1/exoskeleton_0.1.1_Darwin_arm64.tar.gz"
      sha256 "faa10da85a798d8db0463fa62f24ccda1d08e0781f2c5848b7e14257bc1d14b0"

      def install
        bin.install "exoskeleton"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/exoskeleton/releases/download/v0.1.1/exoskeleton_0.1.1_Linux_armv6.tar.gz"
      sha256 "7cb94b22267121da4960477918e0e07c097ff1df0ec35c79df931ceda6b6f8a0"

      def install
        bin.install "exoskeleton"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/exoskeleton/releases/download/v0.1.1/exoskeleton_0.1.1_Linux_x86_64.tar.gz"
      sha256 "1c5360765d5525cddede010bc28cfc3911e569ae96520106ec486d1857c666a9"

      def install
        bin.install "exoskeleton"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/exoskeleton/releases/download/v0.1.1/exoskeleton_0.1.1_Linux_arm64.tar.gz"
      sha256 "8a189305dabf2536fe92260ddc4803e56461972fca25b0a02091b3808a6eb3bd"

      def install
        bin.install "exoskeleton"
      end
    end
  end
end
