# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exoskeleton < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/pricewatcher/releases/download/v0.0.1/exoskeleton_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "8c6c04a1cefd0ff686d98e1b404b4c55f8345b333debce068b084b58c7f59cfe"

      def install
        bin.install "exoskeleton"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/pricewatcher/releases/download/v0.0.1/exoskeleton_0.0.1_Darwin_arm64.tar.gz"
      sha256 "3371c31cadb1506868c8fd20258e1bb51b73e5c23d3a26106eede79753234acb"

      def install
        bin.install "exoskeleton"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/pricewatcher/releases/download/v0.0.1/exoskeleton_0.0.1_Linux_armv6.tar.gz"
      sha256 "7422cff618bfeee18cbb745b3a7f1b3f25f0e7725337be19b35cc36027ec8089"

      def install
        bin.install "exoskeleton"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/pricewatcher/releases/download/v0.0.1/exoskeleton_0.0.1_Linux_x86_64.tar.gz"
      sha256 "8afe81e0039ee47d2619f2dac005781ab112f1d8e400a9d9c5110772d5a4f128"

      def install
        bin.install "exoskeleton"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/pricewatcher/releases/download/v0.0.1/exoskeleton_0.0.1_Linux_arm64.tar.gz"
      sha256 "c3242bc7841564e2354ac028438477e86a63b8fc0bfa37fa7a4711df74678d75"

      def install
        bin.install "exoskeleton"
      end
    end
  end
end
