# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitAutoMessage < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/git-auto-message/releases/download/v0.0.3/git-auto-message_Darwin_x86_64.tar.gz"
      sha256 "4d0ad21735ea1cfc5af85ee66260626a78d714ea933e779e28261d2bd14ece48"

      def install
        bin.install "git-auto-message"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/git-auto-message/releases/download/v0.0.3/git-auto-message_Darwin_arm64.tar.gz"
      sha256 "ca8846748d7ba4d5504b8c3fd7afb9e6cd1c766556bd22186af9e696159dc628"

      def install
        bin.install "git-auto-message"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pthomison/git-auto-message/releases/download/v0.0.3/git-auto-message_Linux_x86_64.tar.gz"
        sha256 "e57c721174f62695a028d6f9a072fde9363efbba862312e81fc8a49b0c8af9dd"

        def install
          bin.install "git-auto-message"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pthomison/git-auto-message/releases/download/v0.0.3/git-auto-message_Linux_arm64.tar.gz"
        sha256 "93ee1eef747510bf9a8990851396b2bd943e03802fa3621847407d211ec6f482"

        def install
          bin.install "git-auto-message"
        end
      end
    end
  end
end
