# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoHelloworld < Formula
  desc ""
  homepage ""
  version "0.0.5"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/pthomison/go-helloworld/releases/download/0.0.5/go-helloworld_0.0.5_Darwin_x86_64.tar.gz"
    sha256 "e50e00a9871d6543ddc04b5a7cfe558368f9045d97eb34a8de9c2a58dc76172b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/pthomison/go-helloworld/releases/download/0.0.5/go-helloworld_0.0.5_Linux_x86_64.tar.gz"
    sha256 "5f910bfab011a503a9949fda6879c7dd3ec07c770607bd5ec3fde3314d3d3b38"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/pthomison/go-helloworld/releases/download/0.0.5/go-helloworld_0.0.5_Linux_arm64.tar.gz"
    sha256 "3f6690925117b370ab48d793669749ffd5aef4c101aa7bcbf77577779627ecfe"
  end

  def install
    bin.install "go-helloworld"
  end
end
