# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoHelloworld < Formula
  desc ""
  homepage ""
  version "0.0.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/pthomison/go-helloworld/releases/download/0.0.4/go-helloworld_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "b063aa5c8e60d88a8ca6fecace40c975b381124acbf5f87225b024c72afa453d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/pthomison/go-helloworld/releases/download/0.0.4/go-helloworld_0.0.4_Linux_x86_64.tar.gz"
    sha256 "3cb9aa5fed1f938e65faeb7e414e45af6a1f397b6c18e24c346dc7bb80f0f93e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/pthomison/go-helloworld/releases/download/0.0.4/go-helloworld_0.0.4_Linux_arm64.tar.gz"
    sha256 "633d94a9989be39a1a32bb006281322f74cab5358799cc7aac934299820829d7"
  end

  def install
    bin.install "go-helloworld"
  end
end
