# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3auto < Formula
  desc ""
  homepage ""
  version "0.0.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/k3auto/releases/download/v0.0.12/k3auto_0.0.12_darwin_amd64.tar.gz"
      sha256 "03b2b5cd9668075da17eeecda7867a7188fba8152951f3807c73f66bd03b1f30"

      def install
        bin.install "k3auto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/k3auto/releases/download/v0.0.12/k3auto_0.0.12_darwin_arm64.tar.gz"
      sha256 "7c5cd84927bc61dedb1b9e3d987d3b1f854905eba68e3b94a26174ed7409e965"

      def install
        bin.install "k3auto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/k3auto/releases/download/v0.0.12/k3auto_0.0.12_linux_amd64.tar.gz"
      sha256 "20d86ba26c3ea6c05e9704ecd2707c011c9dd1490e0ab0a4cc4bf0c335cf0f45"

      def install
        bin.install "k3auto"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/k3auto/releases/download/v0.0.12/k3auto_0.0.12_linux_armv6.tar.gz"
      sha256 "99e8aefc8816011d1f9fb08198206c18fc042261baa5a26023c95d66905b4ce3"

      def install
        bin.install "k3auto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/k3auto/releases/download/v0.0.12/k3auto_0.0.12_linux_arm64.tar.gz"
      sha256 "3c6015b7ea9e21a1f2c0714ccbe7e171cd041ec54b9520dfffcfb57aa0aa9abd"

      def install
        bin.install "k3auto"
      end
    end
  end
end
