# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3auto < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/k3auto/releases/download/v0.0.1/k3auto_0.0.1_darwin_amd64.tar.gz"
      sha256 "552854d412e0851f16dd8ebee751f9df23a3d27a06cac8b5b2755aaf57f90c07"

      def install
        bin.install "k3auto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/k3auto/releases/download/v0.0.1/k3auto_0.0.1_darwin_arm64.tar.gz"
      sha256 "b7e003ebffc0cc07a46e5b690d36e6f0137ddd1ea62a9cb1db1f968314a6668f"

      def install
        bin.install "k3auto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/k3auto/releases/download/v0.0.1/k3auto_0.0.1_linux_armv6.tar.gz"
      sha256 "7ec5e0f9be7724a980766ab4ab1befb38b1128ae834257dfcff6a764cb4303af"

      def install
        bin.install "k3auto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/k3auto/releases/download/v0.0.1/k3auto_0.0.1_linux_arm64.tar.gz"
      sha256 "a6cf0bb0c42fc6e293e0799377e693dc11a8732181eea69c1c83cebc132faefc"

      def install
        bin.install "k3auto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/k3auto/releases/download/v0.0.1/k3auto_0.0.1_linux_amd64.tar.gz"
      sha256 "35b5e094bef0fb91eb0aa1b3166f87c7d3b04274db4b62f2d7cca5324b298dfd"

      def install
        bin.install "k3auto"
      end
    end
  end
end
