# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3auto < Formula
  desc ""
  homepage ""
  version "0.0.22"

  on_macos do
    on_intel do
      url "https://github.com/pthomison/k3auto/releases/download/v0.0.22/k3auto_0.0.22_darwin_amd64.tar.gz"
      sha256 "fe9419af7ad951ea805df450e497e9e8be5583652f6fa9d616adbdb74e427368"

      def install
        bin.install "k3auto"
      end
    end
    on_arm do
      url "https://github.com/pthomison/k3auto/releases/download/v0.0.22/k3auto_0.0.22_darwin_arm64.tar.gz"
      sha256 "086204d047f2b15219b3e008f974b10c8673101160eb8dc3d8bb5f61506f7d2c"

      def install
        bin.install "k3auto"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pthomison/k3auto/releases/download/v0.0.22/k3auto_0.0.22_linux_amd64.tar.gz"
        sha256 "790d60a7202cec92d5bb888410f5b98cefbae36e8ab40d9170a64d9cbeb7c734"

        def install
          bin.install "k3auto"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/pthomison/k3auto/releases/download/v0.0.22/k3auto_0.0.22_linux_armv6.tar.gz"
        sha256 "01ad9d449e6c162a9b72aff43ae246b1d03770fd8a620cf8ebd23fd1e94fa572"

        def install
          bin.install "k3auto"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pthomison/k3auto/releases/download/v0.0.22/k3auto_0.0.22_linux_arm64.tar.gz"
        sha256 "9f143ded349cc159f38d71d16bcc2331e2028706c58a3ff3951960d0c60aec42"

        def install
          bin.install "k3auto"
        end
      end
    end
  end
end
