# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3dAsAService < Formula
  desc ""
  homepage ""
  version "0.0.3"

  depends_on "k3d"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.3/k3d-as-a-service_0.0.3_Darwin_arm64.tar.gz"
      sha256 "0b8eec21c00138815fd9c42a7280c70fd86b671251a699f7de5c7cf94af09e84"

      def install
        bin.install "k3d-as-a-service"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.3/k3d-as-a-service_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "a91f6f9e0021dcd429f8564bf780452d35dab4412c432387c7beccefe9142b48"

      def install
        bin.install "k3d-as-a-service"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.3/k3d-as-a-service_0.0.3_Linux_armv6.tar.gz"
      sha256 "58088dbaf9b1a0e2aa50d09a15b047ee851ab68f66d3bac195ea4586f18e391f"

      def install
        bin.install "k3d-as-a-service"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.3/k3d-as-a-service_0.0.3_Linux_x86_64.tar.gz"
      sha256 "88dc9e126a30c0d0520e546cf5750261284cda5b3feb701f2db7608d1119d3fc"

      def install
        bin.install "k3d-as-a-service"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.3/k3d-as-a-service_0.0.3_Linux_arm64.tar.gz"
      sha256 "3ceb4ae0ff1b8b1798d17ccf844dcbae37ff804fea3bba74a031897aa0058246"

      def install
        bin.install "k3d-as-a-service"
      end
    end
  end

  service do
    working_dir /Users/pthomison/Projects/kubernetes/flux-environments
    run /usr/bin/make k3d-bootstrap
  end
end
