# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3dAsAService < Formula
  desc ""
  homepage ""
  version "0.0.4"

  depends_on "k3d"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.4/k3d-as-a-service_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "584f6f75af0bb308a330e4ef07c7edd65a141f016e593f53aa1d8d146cc5d8f6"

      def install
        bin.install "k3d-as-a-service"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.4/k3d-as-a-service_0.0.4_Darwin_arm64.tar.gz"
      sha256 "9f3f9798d9dbd8e5d3a43284b32ec6747d4b2950788eeb992ba8834589a65284"

      def install
        bin.install "k3d-as-a-service"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.4/k3d-as-a-service_0.0.4_Linux_armv6.tar.gz"
      sha256 "eb5ea07c14cfe25fd35e8c078604505603b5bd36e831e431e3981143c24a8386"

      def install
        bin.install "k3d-as-a-service"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.4/k3d-as-a-service_0.0.4_Linux_x86_64.tar.gz"
      sha256 "464bcce6a5021e3e6d4677c45359b5d2297f7c595bd60e54e6bb111aefc86ad4"

      def install
        bin.install "k3d-as-a-service"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.4/k3d-as-a-service_0.0.4_Linux_arm64.tar.gz"
      sha256 "c03b821281889612f026742a62a5bacc34d14ff417a5408048cdaac4cf0f6d66"

      def install
        bin.install "k3d-as-a-service"
      end
    end
  end

  service do
    working_dir /Users/pthomison/Projects/kubernetes/flux-environments
    run ["/usr/bin/make", "k3d-bootstrap"]
  end
end
