# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3dAsAService < Formula
  desc ""
  homepage ""
  version "0.0.5"

  depends_on "k3d"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.5/k3d-as-a-service_0.0.5_Darwin_x86_64.tar.gz"
      sha256 "7c845ecebe87b689137bf1f3149d02285397e0a81004904ac44f728691d72d0f"

      def install
        bin.install "k3d-as-a-service"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.5/k3d-as-a-service_0.0.5_Darwin_arm64.tar.gz"
      sha256 "df048a9f6c2236622645bead74be153683521e0427e3c070c8db7a47050959ff"

      def install
        bin.install "k3d-as-a-service"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.5/k3d-as-a-service_0.0.5_Linux_armv6.tar.gz"
      sha256 "4463fd94a1b1b8f1b4d42744625df7b032a9241b23fe74eb5d4605fc42dba965"

      def install
        bin.install "k3d-as-a-service"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.5/k3d-as-a-service_0.0.5_Linux_x86_64.tar.gz"
      sha256 "e79df8c0fc92a7f89a89bc9c6cac6742b71ec60e84dcbbbd8acc105ed01a75fa"

      def install
        bin.install "k3d-as-a-service"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/k3d-as-a-service/releases/download/v0.0.5/k3d-as-a-service_0.0.5_Linux_arm64.tar.gz"
      sha256 "85c9c182e652613c9e7276f3e8c0b9eef744bfa7c11882d4125ec592ff20cdfb"

      def install
        bin.install "k3d-as-a-service"
      end
    end
  end

  service do
    run ["/usr/bin/make", "k3d-bootstrap"]
    working_dir "/Users/pthomison/Projects/kubernetes/flux-environments"
  end
end
