# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K3sHelper < Formula
  desc ""
  homepage ""
  version "0.0.3"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/pthomison/k3s-helper/releases/download/0.0.3/k3s-helper_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "f4bdb02226f266cc4911ad04d2e47073de45373e895ce255460f5f27658f0697"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/pthomison/k3s-helper/releases/download/0.0.3/k3s-helper_0.0.3_Linux_x86_64.tar.gz"
    sha256 "76c729cdb14e986a5b5eda23c5c3bcc2827a1e283f2421843e88a5865b12ceca"
  end

  def install
    bin.install "k3s-helper"
  end
end
