# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pricewatcher < Formula
  desc ""
  homepage ""
  version "0.0.19"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/pricewatcher/releases/download/v0.0.19/pricewatcher_0.0.19_Darwin_arm64.tar.gz"
      sha256 "a06ce084b3af34b871e91cbf9f94eef49b006a2a0ad39c6f092f9409e5a505be"

      def install
        bin.install "pricewatcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/pricewatcher/releases/download/v0.0.19/pricewatcher_0.0.19_Darwin_x86_64.tar.gz"
      sha256 "567f544a1a3e51dfea6a1e2a4c4872632518e64209651dc604fb992c81d8883c"

      def install
        bin.install "pricewatcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/pricewatcher/releases/download/v0.0.19/pricewatcher_0.0.19_Linux_armv6.tar.gz"
      sha256 "e31b760e60f8966393595f65f1fe75b16c1ec523d620ce15f57c134dad9b86b3"

      def install
        bin.install "pricewatcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/pricewatcher/releases/download/v0.0.19/pricewatcher_0.0.19_Linux_x86_64.tar.gz"
      sha256 "5bcb59a707128fec51744097a166c2bf3f608441d83bf5083f023523b8dbc1de"

      def install
        bin.install "pricewatcher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/pricewatcher/releases/download/v0.0.19/pricewatcher_0.0.19_Linux_arm64.tar.gz"
      sha256 "8fb1557e7917378ae0dacda19b503334ff71ec73d9e94b5a8bef4a0c14b45859"

      def install
        bin.install "pricewatcher"
      end
    end
  end
end
