# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SsmK8sInjector < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/ssm-k8s-injector/releases/download/0.0.1/ssm-k8s-injector_0.0.1_Darwin_arm64.tar.gz"
      sha256 "92d9832d831d23c8937abc275335aa03e0b8335ce094835e8e260d66829276ad"

      def install
        bin.install "ssm-k8s-injector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/ssm-k8s-injector/releases/download/0.0.1/ssm-k8s-injector_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "a2573cd45077b6fa08a77f34895497156dadebf08a06fded293b2119747ea7ce"

      def install
        bin.install "ssm-k8s-injector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/ssm-k8s-injector/releases/download/0.0.1/ssm-k8s-injector_0.0.1_Linux_armv6.tar.gz"
      sha256 "49d60d1235a83f7f5368a54efe2c4132336c20b640ac4757af154ccbd15451ed"

      def install
        bin.install "ssm-k8s-injector"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/ssm-k8s-injector/releases/download/0.0.1/ssm-k8s-injector_0.0.1_Linux_arm64.tar.gz"
      sha256 "fbc39deab1de06a963dcd754f9ce5bb7219c9c948887bae21abe33dcd9ba4207"

      def install
        bin.install "ssm-k8s-injector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/ssm-k8s-injector/releases/download/0.0.1/ssm-k8s-injector_0.0.1_Linux_x86_64.tar.gz"
      sha256 "d6cdb75d6b13ef1fd42a9c2239d4ffe843840696b55734e6f11c687946b16622"

      def install
        bin.install "ssm-k8s-injector"
      end
    end
  end
end
