# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SsmK8sInjector < Formula
  desc ""
  homepage ""
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/ssm-k8s-injector/releases/download/0.0.6/ssm-k8s-injector_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "7e4a33c18133d802f7a6a4fd287d7848cbe53284215584c7c8436e9999f090bd"

      def install
        bin.install "ssm-k8s-injector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/ssm-k8s-injector/releases/download/0.0.6/ssm-k8s-injector_0.0.6_Darwin_arm64.tar.gz"
      sha256 "8c061ed050423868a1a71be1f607627c5340ecf752f4b4b0a1fa7e36c5f97783"

      def install
        bin.install "ssm-k8s-injector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/ssm-k8s-injector/releases/download/0.0.6/ssm-k8s-injector_0.0.6_Linux_arm64.tar.gz"
      sha256 "02b3cb87903260a17fd8719b3686d2f581ec577112ca30c3d0056c3857d892c3"

      def install
        bin.install "ssm-k8s-injector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/ssm-k8s-injector/releases/download/0.0.6/ssm-k8s-injector_0.0.6_Linux_x86_64.tar.gz"
      sha256 "3ded8f81fa1e435170abc436a0f9b90cb5e8114968b77fb41ade5cfb0d4d1846"

      def install
        bin.install "ssm-k8s-injector"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/ssm-k8s-injector/releases/download/0.0.6/ssm-k8s-injector_0.0.6_Linux_armv6.tar.gz"
      sha256 "394ae8eb55812fae99b2d068bd069cb449c3b988c1ad0b65418079e8547f4106"

      def install
        bin.install "ssm-k8s-injector"
      end
    end
  end
end
