# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TailscaleDnsReflector < Formula
  desc ""
  homepage ""
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/tailscale-dns-reflector/releases/download/v0.0.1/tailscale-dns-reflector_Darwin_x86_64.tar.gz"
      sha256 "a72b5dc01f6289f0b592f593309b522101a860003de4e2aece8f494aadcb765c"

      def install
        bin.install "tailscale-dns-reflector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/tailscale-dns-reflector/releases/download/v0.0.1/tailscale-dns-reflector_Darwin_arm64.tar.gz"
      sha256 "922e91a6a3649fad1e8bd44d3fbdaea9c2861391c014a3c8f01b61d40457545f"

      def install
        bin.install "tailscale-dns-reflector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pthomison/tailscale-dns-reflector/releases/download/v0.0.1/tailscale-dns-reflector_Linux_x86_64.tar.gz"
        sha256 "c1bb7e7a38e1cb484590c8259e659e1410bf93af4478e4f6026d1676de17de82"

        def install
          bin.install "tailscale-dns-reflector"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pthomison/tailscale-dns-reflector/releases/download/v0.0.1/tailscale-dns-reflector_Linux_arm64.tar.gz"
        sha256 "4829c19b6dd5555157a2f5eb80a10dc85c9a427a958222801443f5d551f75886"

        def install
          bin.install "tailscale-dns-reflector"
        end
      end
    end
  end
end
