# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TailscaleDnsReflector < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/tailscale-dns-reflector/releases/download/v0.0.2/tailscale-dns-reflector_Darwin_x86_64.tar.gz"
      sha256 "a7e37080c288f3fedcbc80f0dd1b509f4a590863aaf3310de9efc3b4ab69ce84"

      def install
        bin.install "tailscale-dns-reflector"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/tailscale-dns-reflector/releases/download/v0.0.2/tailscale-dns-reflector_Darwin_arm64.tar.gz"
      sha256 "0b108c3ccaf5058be5414c922de8f0536b7ca4f0b488c8b2e9e50559daccfe3f"

      def install
        bin.install "tailscale-dns-reflector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pthomison/tailscale-dns-reflector/releases/download/v0.0.2/tailscale-dns-reflector_Linux_x86_64.tar.gz"
        sha256 "ced2a014dc2bf11a5dae007fb38a28a58f94385d25f883d7daff477b3ec31565"

        def install
          bin.install "tailscale-dns-reflector"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pthomison/tailscale-dns-reflector/releases/download/v0.0.2/tailscale-dns-reflector_Linux_arm64.tar.gz"
        sha256 "7a97e63d77305be81f6b2f304469d19c3873107f116ac70cb57bf3981f02689b"

        def install
          bin.install "tailscale-dns-reflector"
        end
      end
    end
  end
end
