# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wikindexer < Formula
  desc ""
  homepage ""
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/wikindexer/releases/download/v0.0.5/wikindexer_0.0.5_darwin_arm64.tar.gz"
      sha256 "6c04a9d0cd573b9aa1dba0363c8b31ad7d68743463ae991cdb1a747c0e507cd9"

      def install
        bin.install "wikindexer-collector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/wikindexer/releases/download/v0.0.5/wikindexer_0.0.5_darwin_amd64.tar.gz"
      sha256 "c22aca2fca2d515808816678312aafd2fb28c5a04553970141b80e2af54cbaf7"

      def install
        bin.install "wikindexer-collector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/wikindexer/releases/download/v0.0.5/wikindexer_0.0.5_linux_arm64.tar.gz"
      sha256 "7adc8b83684ebfeb626d60696e728a18a802e8597d64fe1c08f1fcc3440531ed"

      def install
        bin.install "wikindexer-collector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/wikindexer/releases/download/v0.0.5/wikindexer_0.0.5_linux_amd64.tar.gz"
      sha256 "695c4c4f1ea7d924a6216eedc2515d17589c60dd15e02b6e49b40a876103e513"

      def install
        bin.install "wikindexer-collector"
      end
    end
  end

  def post_install
    (var/"lib/wikindexer").mkpath
  end

  service do
    run opt_bin/"wikindexer-collector"
    log_path var/"log/wikindexer-collector-stdout.log"
    error_log_path var/"log/wikindexer-collector-stderr.log"
    working_dir var/"lib/wikindexer"
  end
end
