# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wikindexer < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/wikindexer/releases/download/v0.0.3/wikindexer_0.0.3_darwin_arm64.tar.gz"
      sha256 "ec7be15d8f83288c80afd725a057819b380fe5e5438157e8ee6231971438d9f8"

      def install
        bin.install "wikindexer-collector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/wikindexer/releases/download/v0.0.3/wikindexer_0.0.3_darwin_amd64.tar.gz"
      sha256 "49b8b5e82a59bf721aee2d39f28eb79b56bb8c16617551d0be52a2e049034d32"

      def install
        bin.install "wikindexer-collector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/wikindexer/releases/download/v0.0.3/wikindexer_0.0.3_linux_arm64.tar.gz"
      sha256 "eb4694e4bd9de1d1959cf6df9148a8de9cd26399d8a0999ebe8f7bd06a749495"

      def install
        bin.install "wikindexer-collector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/wikindexer/releases/download/v0.0.3/wikindexer_0.0.3_linux_amd64.tar.gz"
      sha256 "e031ecc5d370fff95e56e5f123a9daa0e0a789d56526d9afa245ef6544d2fe7c"

      def install
        bin.install "wikindexer-collector"
      end
    end
  end

  def post_install
    (var/"lib/wikindexer").mkpath
  end

  service do
    run opt_bin/"wikindexer"
    log_path var/"log/wikindexer-stdout.log"
    error_log_path var/"log/wikindexer-stderr.log"
    working_dir var/"lib/wikindexer"
  end
end
