# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wikindexer < Formula
  desc ""
  homepage ""
  version "0.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pthomison/wikindexer/releases/download/v0.0.6/wikindexer_0.0.6_darwin_arm64.tar.gz"
      sha256 "04ec348c0715c47019f6d46aef7c76f5109c8fb58cf3742f151f5aba175f2b16"

      def install
        bin.install "wikindexer-collector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/wikindexer/releases/download/v0.0.6/wikindexer_0.0.6_darwin_amd64.tar.gz"
      sha256 "80974aa0867bdf3144962420d1bd7467fa0721e0e94b19c008c09e395c149170"

      def install
        bin.install "wikindexer-collector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pthomison/wikindexer/releases/download/v0.0.6/wikindexer_0.0.6_linux_arm64.tar.gz"
      sha256 "e4d9a88f272a1be68b309f4093b2811f9996ad6af103ecaf64ca2b77a46fa10a"

      def install
        bin.install "wikindexer-collector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pthomison/wikindexer/releases/download/v0.0.6/wikindexer_0.0.6_linux_amd64.tar.gz"
      sha256 "fa7e7b89996979d51343462385208865d45fd0982daf96341538e0b4a610eb80"

      def install
        bin.install "wikindexer-collector"
      end
    end
  end

  def post_install
    (var/"lib/wikindexer").mkpath
  end

  service do
    run opt_bin/"wikindexer-collector"
    log_path var/"log/wikindexer-collector-stdout.log"
    error_log_path var/"log/wikindexer-collector-stderr.log"
    working_dir var/"lib/wikindexer"
  end
end
